#!/usr/bin/env bash
# Install + configure coturn (self-hosted TURN) on the CallBot VPS.
#
# Why: third-party TURN providers (openrelay, metered.ca free tier, etc.)
# sometimes drop ICE consent-freshness packets, killing calls after ~30s.
# Self-hosted coturn on the same box has zero network hops on the server
# side, so the connection cannot die from server-side packet loss.
#
# Targets Amazon Linux 2023 + ec2-user with passwordless sudo.
#
# Usage:
#   cd ~/CallBot
#   chmod +x scripts/install_coturn.sh
#   sudo ./scripts/install_coturn.sh
#
# Idempotent: safe to re-run.

set -euo pipefail

DOMAIN="callbot.duckdns.org"
APP_DIR="/home/ec2-user/CallBot"
ENV_FILE="$APP_DIR/.env"
PUBLIC_IP="$(curl -fsS --max-time 5 https://api.ipify.org)"
PRIVATE_IP="$(ip -4 -o addr show ens5 2>/dev/null | awk '{print $4}' | cut -d/ -f1)"
[ -n "$PRIVATE_IP" ] || PRIVATE_IP="$(hostname -I | awk '{print $1}')"

phase() { echo; echo "============================================================"; echo "  $1"; echo "============================================================"; }
ok()    { echo "  [OK] $1"; }
note()  { echo "  [..] $1"; }
warn()  { echo "  [!!] $1" >&2; }
die()   { echo "  [XX] $1" >&2; exit 1; }

[ "$(id -u)" -eq 0 ] || die "run with sudo"
[ -f "$ENV_FILE" ] || die "$ENV_FILE not found — run deploy_vps.sh first"

# --- 1. Install coturn ------------------------------------------------------

phase "1. Install coturn"
if ! command -v turnserver >/dev/null 2>&1; then
    # AL2023 ships no coturn. Add EPEL as a plain repo file (the
    # epel-release RPM fails on AL2023 because it requires redhat-release).
    if [ ! -f /etc/yum.repos.d/epel.repo ]; then
        cat > /etc/yum.repos.d/epel.repo <<'EOF'
[epel]
name=Extra Packages for Enterprise Linux 9 - $basearch
metalink=https://mirrors.fedoraproject.org/metalink?repo=epel-9&arch=$basearch
enabled=1
gpgcheck=1
gpgkey=https://dl.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL-9
EOF
        note "added EPEL 9 repo at /etc/yum.repos.d/epel.repo"
    fi
    dnf -y -q install coturn
    ok "coturn installed"
else
    ok "coturn already present"
fi

# --- 2. Generate credentials -----------------------------------------------

phase "2. Generate credentials"
CRED_FILE=/etc/coturn/callbot.cred
mkdir -p /etc/coturn
if [ ! -f "$CRED_FILE" ]; then
    TURN_USER="callbot"
    TURN_PASS="$(openssl rand -base64 32 | tr -d '/+=' | head -c 32)"
    {
        echo "TURN_USER=$TURN_USER"
        echo "TURN_PASS=$TURN_PASS"
    } > "$CRED_FILE"
    chmod 600 "$CRED_FILE"
    ok "fresh credentials at $CRED_FILE"
else
    # shellcheck disable=SC1090
    source "$CRED_FILE"
    ok "reusing existing credentials at $CRED_FILE"
fi

# --- 3. Configure /etc/turnserver.conf --------------------------------------

phase "3. Write /etc/turnserver.conf"
# Try to use the Let's Encrypt cert if present (for TURNS on 5349).
CERT_LINE=""
KEY_LINE=""
if [ -f "/etc/letsencrypt/live/$DOMAIN/fullchain.pem" ]; then
    CERT_LINE="cert=/etc/letsencrypt/live/$DOMAIN/fullchain.pem"
    KEY_LINE="pkey=/etc/letsencrypt/live/$DOMAIN/privkey.pem"
    # coturn runs as user 'coturn' — let it read the certs.
    chmod 0755 /etc/letsencrypt/{live,archive} 2>/dev/null || true
fi

cat > /etc/turnserver.conf <<EOF
# CallBot coturn config — generated by install_coturn.sh

# --- network ---
listening-port=3478
tls-listening-port=5349

# Bind to private interface; advertise public IP to clients.
listening-ip=$PRIVATE_IP
external-ip=$PUBLIC_IP/$PRIVATE_IP
relay-ip=$PRIVATE_IP

# Relay UDP port range — must match the AWS Security Group rule.
min-port=49152
max-port=65535

# --- auth (long-term credentials) ---
lt-cred-mech
realm=$DOMAIN
user=$TURN_USER:$TURN_PASS

# --- TLS (only enabled if Let's Encrypt cert exists) ---
$CERT_LINE
$KEY_LINE
no-tlsv1
no-tlsv1_1

# --- safety / hardening ---
no-cli
no-multicast-peers
no-loopback-peers
denied-peer-ip=10.0.0.0-10.255.255.255
denied-peer-ip=172.16.0.0-172.31.255.255
denied-peer-ip=192.168.0.0-192.168.255.255
denied-peer-ip=169.254.0.0-169.254.255.255
denied-peer-ip=127.0.0.0-127.255.255.255

# Quiet the log a bit.
no-stdout-log
log-file=/var/log/coturn/turnserver.log
simple-log

fingerprint
EOF
chmod 644 /etc/turnserver.conf
mkdir -p /var/log/coturn
chown coturn:coturn /var/log/coturn 2>/dev/null || true
ok "config written"

# --- 4. Enable and start coturn --------------------------------------------

phase "4. Enable + start coturn"
# The default unit reads /etc/sysconfig/coturn for command-line args.
# Some packages disable coturn by default via that file; make sure it's on.
if [ -f /etc/sysconfig/coturn ]; then
    sed -i 's/^TURNSERVER_ENABLED=.*/TURNSERVER_ENABLED=1/' /etc/sysconfig/coturn
fi
systemctl daemon-reload
systemctl enable --now coturn >/dev/null
sleep 2
if systemctl is-active --quiet coturn; then
    ok "coturn service is active"
else
    journalctl -u coturn -n 30 --no-pager
    die "coturn failed to start"
fi

# --- 5. Update .env -- put local TURN first, keep metered.ca as fallback ----

phase "5. Update $ENV_FILE"
NEW_URLS="turn:$DOMAIN:3478?transport=udp,turn:$DOMAIN:3478?transport=tcp"
if [ -n "$CERT_LINE" ]; then
    NEW_URLS="$NEW_URLS,turns:$DOMAIN:5349?transport=tcp"
fi
# Optional: append the existing TURN_URLS as a fallback (commented out
# below; uncomment if you want belt+suspenders).
# OLD_URLS="$(grep -E '^TURN_URLS=' "$ENV_FILE" | sed -E "s/^TURN_URLS=['\"]?(.+)['\"]?$/\1/")"
# NEW_URLS="$NEW_URLS,$OLD_URLS"

# Replace in place; keep a .bak so this is reversible.
cp "$ENV_FILE" "$ENV_FILE.bak.coturn"
sed -i -E \
    -e "s|^TURN_URLS=.*|TURN_URLS='$NEW_URLS'|" \
    -e "s|^TURN_USERNAME=.*|TURN_USERNAME='$TURN_USER'|" \
    -e "s|^TURN_CREDENTIAL=.*|TURN_CREDENTIAL='$TURN_PASS'|" \
    "$ENV_FILE"
ok ".env updated (backup at $ENV_FILE.bak.coturn)"

# --- 6. Restart callbot ----------------------------------------------------

phase "6. Restart callbot"
systemctl restart callbot
sleep 3
systemctl is-active --quiet callbot || {
    journalctl -u callbot -n 30 --no-pager
    die "callbot failed to restart"
}
ok "callbot restarted, using self-hosted TURN"

# --- 7. Print SG checklist -------------------------------------------------

phase "7. AWS Security Group — REQUIRED inbound rules"
cat <<EOF

  YOU MUST OPEN THESE PORTS in the AWS console (EC2 -> SG -> Inbound):

    UDP   3478              Source 0.0.0.0/0    TURN UDP
    TCP   3478              Source 0.0.0.0/0    TURN TCP
    UDP   49152-65535       Source 0.0.0.0/0    TURN relay range
EOF
if [ -n "$CERT_LINE" ]; then
cat <<EOF
    TCP   5349              Source 0.0.0.0/0    TURNS over TLS (optional but recommended)
EOF
fi
cat <<EOF

  Until those rules exist, only the same-VPS path works.

  TURN URL the server will advertise: turn:$DOMAIN:3478?transport=udp
  TURN realm:                          $DOMAIN
  TURN username:                       $TURN_USER
  TURN credential:                     $TURN_PASS

  (Credential is also at $CRED_FILE — chmod 600. Don't paste publicly.)

============================================================
  DONE
============================================================

  Live coturn log:  sudo tail -F /var/log/coturn/turnserver.log
  Live callbot log: sudo journalctl -u callbot -f

  Verify it works:
    1) Open the SG ports above.
    2) Browse to https://$DOMAIN/?relay   (relay-only stress test).
    3) If agent greets and conversation works -> coturn is good.

  Revert this change:
    sudo mv $ENV_FILE.bak.coturn $ENV_FILE
    sudo systemctl disable --now coturn
    sudo systemctl restart callbot

EOF
